services:
  db:
    image: mongo:6.0
    container_name: hometasker-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: "${DOCKERHUB_USERNAME}/hometasker-backend:${VERSION}"
    container_name: hometasker-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  frontend:
    build:
      context: ./frontend-v2
      dockerfile: Dockerfile
    image: "${DOCKERHUB_USERNAME}/hometasker-frontend:${VERSION}"
    container_name: hometasker-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
