services:
  db:
    image: mongo:6.0
    container_name: hometasker-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hometasker-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  frontend:
    build:
      context: ./frontend-v2
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "http://localhost:5000"
    container_name: hometasker-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy

volumes:
  mongo_data:
