services:
  mongo:
    image: mongo:6.0
    container_name: hometasker-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hometasker-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend-v2
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "http://localhost:5000/"
    container_name: hometasker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
