version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: hometasker-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hometasker-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      # Point at the mongo service above
      MONGO_URI: "mongodb://mongo:27017/hometasker"
      # test-secret
      TOKEN_SECRET: "demo_secret_key_12345"
      FRONTEND_URL: "http://localhost:3000"

volumes:
  mongo_data:
